spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    mongodb:
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_URI}
      port: ${REDIS_PORT}

  elasticsearch:
    uris: ${ES_URI}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}

gemini:
  api:
    key: ${GEMINI_API_KEY}

logging:
  level:
    root: INFO