spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:13306/crm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: crm
    password: crm

  data:
    mongodb:
      uri: mongodb://localhost:27018/crm
    redis:
      host: localhost
      port: 6380

  elasticsearch:
    uris: http://localhost:9201

  kafka:
    consumer:
      group-id: crm-group
      auto-offset-reset: earliest
    producer:
      acks: all

server:
  port: 8081

app:
  summary-sync:
    cron: "0 * * * * *"
    batch-size: 100
  
gemini:
  api:
    key: ${GEMINI_API_KEY}
