spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:13306/crm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: crm
    password: crm

  data:
    mongodb:
      uri: mongodb://localhost:27018/crm

    redis:
      host: localhost
      port: 6380

  elasticsearch:
    uris: http://localhost:9201

server:
  port: 8081

app:
  summary-sync:
    cron: "0 * * * * *"
    batch-size: 100

gemini:
  api:
    key: ${GEMINI_API_KEY}

historical-batch:
  enabled: true       # true로 변경 후 /api/historical/run 호출 시 배치 시작
  start-date: "2026-01-01"
  end-date: "2026-03-24"
  daily-count: 10    # 일일 생성 건수 ----- 기존 : 1000(하루 1000건 생성)
  chunk-size: 10      # 트랜잭션 1회당 삽입 건수 (consultation_results + raw_texts 등) -- 기존 : 100(1000개 생성 기준)
